import styles from "../styles/CreatePoll.module.css";
import PollCreationForm from "@/components/PollCreationForm";
import { useState } from "react";
import Head from "next/head";

type Options = {
  optionNumber: number;
  key: number;
};

export default function CreatePoll() {
  const [options, setOptions] = useState<Options[]>([
    { optionNumber: 1, key: 1 },
    { optionNumber: 2, key: 2 },
  ]);

  function handleAddOption() {
    const index = options.length + 1;
    const newOptionData = { optionNumber: index, key: index };
    setOptions((prevState) => {
      const updatedOptions = [...prevState];
      updatedOptions.push(newOptionData);
      return updatedOptions;
    });
  }

  function handleLastOptionRemoval() {
    setOptions((prevState) => {
      const updatedOptions = [...prevState];
      updatedOptions.pop();
      return updatedOptions;
    });
  }

  return (
    <>
      <Head>
        <title>Create Poll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <h1 className={styles.title}>Poll Creation</h1>
          <PollCreationForm options={options} />
          <div className={styles.buttonsContainer}>
            <button className={styles.button} onClick={handleAddOption}>
              Add option
            </button>
            <button
              disabled={options.length == 2 ? true : false}
              className={styles.button}
              onClick={handleLastOptionRemoval}
            >
              Remove last option
            </button>
            <button className={styles.button}>Save</button>
          </div>
        </section>
      </main>
    </>
  );
}
