import Head from "next/head";
import Link from "next/link";
import PollCard from "@/components/PollCard";

import styles from "../styles/Home.module.css";
import api from "./api/axios";
import { useEffect, useState } from "react";
import socket from "@/services/socket";

type Poll = {
  id: number;
  title: string;
  total_votes: number;
};

export default function Home() {
  const [polls, setPolls] = useState<Poll[]>([]);

  useEffect(() => {
    function getPolls() {
      api.get("/polls").then((response) => {
        setPolls(response.data);
      });
    }

    getPolls();

    socket.on("updatePolls", (polls: Poll[]) => {
      setPolls(polls);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.mainSection}>
          <h1 className={styles.title}>Running Polls</h1>
          <section className={styles.createPollSection}>
            <Link href="/create-poll">
              <button className={styles.button}>Create poll</button>
            </Link>
          </section>
          <div className={styles.pollCardsContainer}>
            {polls.map((poll) => (
              <PollCard
                key={poll.id}
                pollTitle={poll.title}
                totalVotes={poll.total_votes}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
