import Head from "next/head";
import LoginForm from "@/components/LoginForm";

import { useState } from "react";
import { useRouter } from "next/router";
import styles from "../styles/Login.module.css";
import api from "./api/axios";

type User = {
  id: number;
  username: string;
};

export default function Login() {
  const [username, setUsername] = useState<string>("");
  const [showErrMessage, setShowErrMessage] = useState<boolean>(false);
  const router = useRouter();

  function handleUsernameInput(username: string) {
    setUsername(username);
  }

  function handleRegisterButtonClick(e: any) {
    e.preventDefault();
    api
      .post("/users", {
        username,
      })
      .then((success) => {
        router.push("/");
      })
      .catch((err) => {
        if (err.response.status === 400) {
          setShowErrMessage(true);
        }
      });
  }

  function handleLoginButtonClick(e: any) {
    e.preventDefault();
    api
      .get("/users")
      .then((response) => {
        const users: User[] = response.data;
        const foundUser = users.find((user) => user.username === username);
        if (foundUser) {
          router.push("/");
        }
      })
      .catch((err) => console.log(err));
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <h1 className={styles.loginTitle}>Authentication</h1>
          <LoginForm
            handleUsername={handleUsernameInput}
            handleRegisterClick={handleRegisterButtonClick}
            handleLoginClick={handleLoginButtonClick}
          />
          {showErrMessage && (
            <p className={styles.usernameTakenText}>
              This username is already taken.
            </p>
          )}
        </section>
      </main>
    </>
  );
}
