import styles from "../styles/Login.module.css";
import Head from "next/head";
import LoginForm from "@/components/LoginForm";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <h1 className={styles.loginTitle}>Authentication</h1>
          <LoginForm />
          <p className={`${styles.usernameTakenText} ${styles.hideElement}`}>
            This username is already taken.
          </p>
        </section>
      </main>
    </>
  );
}
